# Generated by Django 5.0.6 on 2024-06-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_seances_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='seances',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
    ]
