# Generated by Django 5.0.6 on 2024-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_alter_books_options_alter_seances_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seances',
            name='date_time',
            field=models.CharField(max_length=20, verbose_name='Дата и время'),
        ),
    ]
